SUM_OPERATION_NAME = 'sum'
SUBTRACT_OPERATION_NAME = 'subtract'
MULTIPLY_OPERATION_NAME = 'multiply'
DIVIDE_OPERATION_NAME = 'divide'

CALCULATION_STATUS_ENQUEUED = 'enqueued'
CALCULATION_STATUS_DONE = 'done'
CALCULATION_STATUS_ERROR = 'error'